Mostrando o resultado em relatório

diff --git a/.github/workflows/ci-junit-v5.yml b/.github/workflows/ci-junit-v5.yml
--- a/.github/workflows/ci-junit-v5.yml
+++ b/.github/workflows/ci-junit-v5.yml
@@ -19,9 +19,12 @@ jobs:
       - name: Test
         #run: mvn --batch-mode -Dmaven.test.failure.ignore=true test
         run: mvn clean test -pl :devops -Dtest=UnitTests
+
+      - name: Reporting
+        run: mvn surefire-report:report  
                 
-      - name: Publish Test Report
-        uses: mikepenz/action-junit-report@v4
-        if: success() || failure() # always run even if the previous step fails
-        with:
-          report_paths: '**/build/test-results/test/TEST-*.xml'
+      #- name: Publish Test Report
+      #  uses: mikepenz/action-junit-report@v4
+      #  if: success() || failure() # always run even if the previous step fails
+      #  with:
+      #    report_paths: '**/build/test-results/test/TEST-*.xml'
